### ISSUE TITLE
Create Wireframe

### ISSUE THREAD

**Issue by CPetrevski** [CPetrevski/urReview#1]
Wireframe Link:
https://docs.google.com/presentation/d/1YuYPjSNoTir_QNM6wPX9UqEysX7l0rGduoFT4AJj2iI/edit?usp=sharing

**Comment by shaotangyen** [comment]
Wireframe Link:
https://docs.google.com/presentation/d/1YuYPjSNoTir_QNM6wPX9UqEysX7l0rGduoFT4AJj2iI/edit?usp=sharing
